name: Docker Image CI & Elastic Beanstalk CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: AWS access
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA227AA22EP5RCU5P4
        aws-secret-access-key: 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
        aws-region: us-east-1
    
    - name: Login to Amazon ECR 
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        env: |
          AWS_ACCESS_KEY_ID: AKIA227AA22EP5RCU5P4
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
        
    - name: Build the Docker image
      run: |
        docker build -t yolox:latest .
        docker tag yolox:latest public.ecr.aws/s4t8p8e0/yolox:latest
        docker push public.ecr.aws/s4t8p8e0/yolox:latest
        
    
    
